[[section-building-block-view]]


== Building Block View

=== Whitebox of the Overall System 

[plantuml, "whitebox-overall-system", png]
----
actor user as "Usuario"
Component WIQ
Component Wikidata

user -right-> WIQ: interactúa
WIQ <-right-> Wikidata: consulta
----

Motivation::
WIQ es una aplicación Web en la que los usuarios puedan registrarse y entrar a jugar. 
El juego consiste en responder una serie de preguntas de diferentes tipos y temáticas obteniendo un premio por cada pregunta acertada.
Un aspecto importante del sistema es que las preguntas serán generadas automáticamente a partir de los datos de Wikidata (https://www.wikidata.org/).

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| Usuario | Interactúa con la aplicación.
| WIQ | Aplicación con la que interactúa el usuario. Se comunica con Wikidata para generar preguntas automáticamente.
| Wikidata | Base de datos colaborativa de conocimiento libre que almacena datos estructurados.
|===

[plantuml, "level-1", png]

----
actor user as "Usuario"

Component web as "WebApp" {
  Component front as "Frontend Web"
  Component back as "Backend"
  Database db as "MongoDB"
}

Component Wikidata

user <-right-> front: interactúa
front <-right-> back: interactúa
back <-right-> db: interactúa
back <-down-> Wikidata: interactúa
----

Motivation::
Muestra los principales componentes de WIQ.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Nombre** | **Responsabildad**
| Usuario | Interactúa con el frontend web de la aplicación.
| Frontend Web | Componente responsable de la interfaz de usuario del sistema. Proporciona acceso a las funcionalidades del sistema a través de un navegador web.
| Backend | Contiene la lógica de negocio y la gestión de datos del sistema. Expone endpoints para interactuar con los clientes a través de API.
| MongoDB | Sistema de gestión de bases de datos NoSQL, que utiliza un modelo de datos flexible basado en documentos JSON con esquemas dinámicos.
| Wikidata | Base de datos colaborativa de conocimiento libre que almacena datos estructurados.
|===
