ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Conceptos transversales


[role="arc42help"]

=== Arquitectura empleada

El sistema contará con una arquitectura basada en microservicios. Dividiremos la aplicación en partes independientes en función de los requisitos de alto nivel de forma que sea sencillo modificar los elementos existentes y añadir nuevos.


=== Interfaz de usuario

La aplicación constará de un ventana "inicio de sesión o registro" que nos permitirá acceder a una vista inicial "Home" desde la que se podrá tanto jugar una partida (opción que nos llevaría a una vista nueva donde vemos el juego), como acceder a las distintas vistas "Perfil de usuario" y "Busqueda de usuarios". Además desde la vista de "Perfil de usuario" podremos acceder a una nueva vista para ver el historial del usuario. A medida que se desarrolle la aplicación se adjuntarán imagenes a este apartado para mostrarlo de forma gráfica.
=== Testabilidad

La aplación debe ser testeable. Queremos implementar tests que nos permitan comprobar el correcto funcionamiento de la misma.


=== Modelo de dominio 

Agregar diagrama despues de consultar con el resto del grupo