ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts


[role="arc42help"]

=== Usabilidad

Queremos que la aplicación sea fácil de emplear para nuestros usuarios. Esto puede mermar otras características como la seguridad pero consideramos prioritaria la usabilidad.


=== Fiabilidad

La aplicación debe ser fiable. Para ello implementaremos métodos que permitan a los usuarios seguir accediendo a la aplicación a pesar de que algunos de los servicios externos no funcionen, como la generación de preguntas en bloque para evitar que una caida de Wikidata repercuta en nuestros usuarios.


=== Testabilidad

La aplación debe ser testeable. Queremos implementar tests que nos permitan comprobar el correcto funcionamiento de la misma.


=== Seguridad

La seguridad no va a ser una prioridad a la hora de desarrollar nuestra aplicación. Si bien sí que queremos tener al menos un nivel bajo de seguridad para que las contraseñas y cuentas de los usuarios no peligren, no queremos implementar metodos de seguridad que reduzgan la usabilidad de la aplicación.


=== Disponibilidad

No es un objetivo prioritario pero de ser posible, la aplicación debe estar disponible todo el tiempo posible.